### ISSUE TITLE
Getting an unknown identifier

### ISSUE THREAD

**Issue by ghost** [kevinresol/hare#1]
Heya! Saw this engine swinging by when I was researching HaxeFlixel.
I'm pretty eager to try it, so there I went.
When I try to build it, I get an error.
"Unknown identifier: shader".
It's located in hare/impl/flixel/display/lighting/Lightingsystem.hx
Is there a way to solve this or am I doing something wrong?

**Comment by kevinresol** [comment]
Oops, let me have a look when i have a gap. For now you can find the file in assets/impl/shaders and move it to the right place.

**Comment by kevinresol** [comment]
Ignore my prev comment. 

I think there are some changes in the haxeflixel api that caused this. Let me have a closer look later.

**Comment by ghost** [comment]
Oh ok, no worries man. 
No rush though, I can wait until it's fixed.
Thx for the fast replies!

**Comment by kevinresol** [comment]
@Froom7 would you open the LightingSystem.hx and replace all occurence of `shader` to `postProcessShader` and see if that works? (https://github.com/HaxeFlixel/flixel/commit/e2d99ecb2ad78fa6d8b0d8532f050916d110f5b8)

I can't test now because I am having other dependency issues at the moment.

**Comment by kevinresol** [comment]
Fixed: https://github.com/kevinresol/hare/commit/eb532ab4641c3b8fb36d3302f572d6469bad1e28
