### ISSUE TITLE
Wishlist?

### ISSUE THREAD

**Issue by larsiusprime** [kevinresol/hare#2]
I have a whoooole bunch of stuff in Defender's Quest that could potentially make its way over here piece by piece. Do you have a little wishlist of RPG like features you'd like that I can compare to what we've got in DQ that might be easy to isolate and port over?

**Comment by kevinresol** [comment]
Basically my original idea is to port / reimplement the scripting engine of rpg maker. But since i am not focusing on games anymore at the moment, I don't really have any wish list. Although  this hare thing is still far from production, free feel to try it out or even take it as foundation and built another engine. 

I will still keep an eye here only i am not sure if i can dedicate time to code anything for this

**Comment by larsiusprime** [comment]
Cool! If you don't mind I might fork it and use it as a basic test bed for abstracting some of the more useful concepts out of Defender's Quest. I can make PR's from that, or if you're too busy I'll just keep plugging on the fork.

Features I can imagine would be useful:
1. Statistics / Level Up Table
2. Centralized class for formulas to make game logic calculations transparent, and avoid [this problem](http://www.shamusyoung.com/twentysidedtale/?p=17585)
3. Branching skill tree system
4. Character Class system
5. Equipment system
6. Inventory system
7. Various other things

Some of it might be too specific to Defender's Quest, but a lot of it is of general use. At some point you have to start being "opinionated" about what the engine will do or not ... ex: is "strength" a stat that's worth hard-coding into an enum, or are _all_ stats user-defined? Perhaps some of these systems could be made modular, so that they don't have cross dependencies and users could put together the best things they need from each.

In any case I like what I see in this foundation and I think I'll have a lot of fun in my fork and I'll contribute back whatever you're interested in.

**Comment by kevinresol** [comment]
That sounds cool! 
No problem just feel free to fork and play around, have fun!
