### ISSUE TITLE
Can't build at all because naming?

### ISSUE THREAD

**Issue by AG-w** [kevinresol/hare#4]
doesn't matter if I want to compile to neko or windows
it will just throw
Error: : `lua` is a reserved compiler flag and cannot be defined from the command line.

all library are latest version

**Comment by kevinresol** [comment]
This is developed against Haxe 3.2 so it may not work with newer haxe

**Comment by AG-w** [comment]
I tried to fixed the naming then I found a lot of deprecated class and unsupported usage, probably gonna need time to reflect code

I guess I'll continue to implement my own RPG-style game

**Comment by AG-w** [comment]
somehow I managed to made it build
but the lighting system has been sacrificed lol

then 2nd map in sample straight up messed up
https://imgur.com/l41ofQq
also performance is terrible, I don't know if that's neko's fault
compiled to windows runs normal

I think the messed up map is due to Haxeflixel changing all negative tile value to 0

I'll probably try if I can fix these few issue
like sound assets fail to load and then finally try to fix lighting system
***
looks like openfl's getPath() is busted, I edited Assets.hx part, sound loaded correctly now.
don't know if I'm able to fix lighting system.
